### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by abenson** [zevv/bucklespring#101]
We're coming up on 5 years and are at 68 (at the time of this issue) commits since the last release.  Are there any plans for another tag?  Thanks!

**Comment by zevv** [comment]
Oh, sure, no problem. Anything that needs changed or done, or shall I just put up a `1.5.0` for current master?

**Comment by abenson** [comment]
I don't there's anything that needs to be done, from my perspective at least.

**Comment by zevv** [comment]
1.5.0 has been tagged.
