### ISSUE TITLE
Not working on Debian

### ISSUE THREAD

**Issue by chupocro** [zevv/bucklespring#103]
This is what happens after running it in Debian inside Virtualbox:

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

After that Ctrl-c has to be pressed to return back to the terminal.

EDIT:
It does work well despite of errors.

**Comment by zevv** [comment]
What you describe looks like an OpenAL problem (the library bucklespring uses to play sound); my guess is that it tries to connect to pulseaudio, can not find the pulse server, then tries to connect to jack, can not connect to that either, tries to start jackd, and then jackd emits the last two error lines.
