### ISSUE TITLE
About Windows build

### ISSUE THREAD

**Issue by 3N4N** [zevv/bucklespring#112]
In the readme, it says, "I think the windows build is currently broken." I just tried it out, and it worked fine.

The makefile didn't work for me, though. I'm using MSys2/mingw64 toolchain. I don't think that's handled in the makefile. I created a cmakefile. But after than everything was simple.

I'll try to build with msvc if you want. Otherwise, I just wanted to say bucklespring works on Windows, too.

(By the way, if you wanna update your makefile to handle msys, I can help. Using cmake probably would've been better, but I don't think you'd be willing to change the whole project structure.)

**Comment by 3N4N** [comment]
@zevv without any feedback within the next Sunday, I'll close this issue (on 26th).

**Comment by zevv** [comment]
Hey Enan, sorry for the silence - I don't spend too much time on buckle anymore, as is probably obvious from the lack of commits and other activity here.

Hostly, I don't care about windows myself, as I don't even have a windows machine to test and run it on. If you want to spend the time and effort to make windows a first class citizen I'd gladly pull your PRs, but I'm likely not going to participate in the fun :)

Thanks!
