### ISSUE TITLE
failed to create event tap on MacOS

### ISSUE THREAD

**Issue by qu1gl3s** [zevv/bucklespring#12]
Once installed, I attempt to run `./buckle` which gives me the following message:

`failed to create event tap`

Unsure how to proceed.

**Comment by zevv** [comment]
Not sure as well, but could you try this:
  
"You need superuser privileges to create the event tap, unless accessibility is enabled. To do so, select the "Enable access for assistive devices"  checkbox in the Universal Access system preference pane."

and let me know the result?

**Comment by qu1gl3s** [comment]
Looks like sudo was all I needed for it to function correctly. So it's working correctly on Mac :)

I also noticed you don't have access to numpad keys for this keyboard. I can happily look into recording those for you but I don't know if the sound will be different depending on the year of the model you have or if that is even really an issue.

**Comment by zevv** [comment]
Yeah, having these buttons recorded on a different keyboard with a different mic and different environment will probably give good results. I guess the best solution would be to simply sample all keys on a full keyboard; I plan to make two or three samples of each key with different velocities anyway to give a bit more natural variation to the sound.
