### ISSUE TITLE
Run bucklespring on Mac OS X

### ISSUE THREAD

**Issue by jpwenzel** [zevv/bucklespring#13]
The README.md says:

> "[…] You need superuser privileges to create the event tap […]"

which works fine:

`$ sudo ./buckle`

I can't seem to get the second option to work, though: ("[…] unless accessibility is enabled. To do so, select the 'Enable access for assistive devices' checkbox in the Universal Access system preference pane."). That setting doesn't seem to be available in OS X 10.11.

**Comment by ssgelm** [comment]
Yeah, I spent some time looking into this and for a CLI app like this the only option is to run as root.  The readme should be updated.

**Comment by zevv** [comment]
README updated, for now it seems that running with root privileges is the only way to get this to work.
