### ISSUE TITLE
Use gcc for linking

### ISSUE THREAD

**Issue by Natureshadow** [zevv/bucklespring#22]
While packaging for Debian, I noticed that g«« is used for linking the buckle binary.

Why is this so? I simply replaced it with gcc, and it works.

The problem with g«« is that it automatically links with libstdc««, which buckle does not use, and thats adds an unnecessary dependency.

If there is no good reason to use g««, please link with gcc instead.

**Comment by zevv** [comment]
There *was* a good reason, but that changed when I changed from freealut
  (which is written in C++) to alure.

  Fixed in 4a93842

**Comment by Natureshadow** [comment]
While at it, please add $CPPFLAGS to CFLAGS.

Btw, the Debian package is ready and awaiting upload ☺!

**Comment by zevv** [comment]
* On 2016-09-18 21:22:17 +0200, Dominik George wrote:
 
> While at it, please add $CPPFLAGS to CFLAGS.

Fixed.

> Btw, the Debian package is ready and awaiting upload ☺!

Thanks!

-- 
:wq
^X^Cy^K^X^C^C^C^C
