### ISSUE TITLE
sudo apt-get install bucklespring, unable to locate package bucklespring

### ISSUE THREAD

**Issue by tarvos21** [zevv/bucklespring#40]
I try to install bucklespring on Ubuntu 16.04, but it tells me that unable to locate bucklespring. I finally clone it to local machine, and make. But it may be a tiny problem. The program is great, thanks very much!

**Comment by Natureshadow** [comment]
Ask the people behind your distribution to backport the bucklespring package from Debian testing.

**Comment by tarvos21** [comment]
Great, just mention it.
