### ISSUE TITLE
Do not issue a sound when an application is grabbing the keyboard

### ISSUE THREAD

**Issue by mirabilos** [zevv/bucklespring#41]
The xterm manpage mentions this nice feature:

       The xterm menu (see MENUS above) contains a Secure Keyboard entry
       which, when enabled, attempts to ensure that all keyboard input is
       directed only to xterm (using the GrabKeyboard protocol request).  When
       an application prompts you for a password (or other sensitive data),
       you can enable Secure Keyboard using the menu, type in the data, and
       then disable Secure Keyboard using the menu again.
    
       ·   This ensures that you know which window is accepting your
           keystrokes.
    
       ·   It cannot ensure that there are no processes which have access to
           your X display that might be observing the keystrokes as well.

The problem here is that bucklespring *is* “observing the keystrokes as well”. Maybe it can detect when another application on the same server uses “the GrabKeyboard protocol request” and, in that case, cease emitting sounds for its duration (maybe even play a toggle sound so the user knows the keyboard is now secured and unsecured, respectively).

This is an inital idea, I did not check yet whether this is actually doable within X11 (I don’t know X11 very well).

**Comment by vain** [comment]
I wonder how this would interfere/play together with applications that grab the keyboard for regular input (as opposed to XTerm which supposedly only does it for "secure" input). Take dmenu for example:

http://git.suckless.org/dmenu/tree/dmenu.c#n194

**Comment by mirabilos** [comment]
Hmm, that would then be silenced as well (so make it an option?), but my understanding is that this is a thing only activated on explicit call and for one or so keypress, right?

Meh, X11 sucks ;)

**Comment by zevv** [comment]
I've been looking into this, but I have not found a viable solution - there can simply be more apps grabbing the keyboard for legitimate reasons, and there's no way to tell them apart.

Closing this issue, sorry
