### ISSUE TITLE
Ubuntu instructions don't work

### ISSUE THREAD

**Issue by tunnuz** [zevv/bucklespring#43]
On ubuntu 16.04 LTS the package is nowhere to be found, do we need a ppa?

**Comment by girst** [comment]
not sure what you are talking about. compiling from source works (all packages in the`apt-get install` command are available) and `snap find bucklespring` lists the package too. 

note that bucklespring uses snap packages (not those for the apt package manager).

**Comment by AbuMaia** [comment]
I am also having trouble.

> abumaia@AbuMaia:~$ sudo apt-get install bucklespring
[sudo] password for abumaia: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bucklespring

**Comment by girst** [comment]
this isn't a debian (apt) package - it's a snap package. the instructions read:

    sudo snap install bucklespring

**Comment by AbuMaia** [comment]
Read the Readme again.

> Installation
Debian
Bucklespring is available in the latest Debian and Ubuntu dev-releases, so you can install with
$ sudo apt-get install bucklespring

**Comment by girst** [comment]
this is debian and ubuntu *devel* (which is 17.04). a poke around in [the repo](http://archive.ubuntu.com/ubuntu/dists/devel/universe/binary-amd64/Packages.gz) shows, it is there. those repos are not the one you have on 16.04 - for that, only a snap package (or compiling from source, which is pretty easy as well) is available

**Comment by ashadiqi** [comment]
Using Ubuntu 16.04 LTS. Snap installation succeeded but the program failed to launch. 
Output from `bucklespring.buckle` : 
`AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
ALSA lib conf.c:3750:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
unable to open default device
`

**Comment by taktiker12** [comment]
chech the dependencies and this 2 files
download from here :  

https://packages.debian.org/stretch/all/bucklespring-data/download
https://packages.debian.org/stretch/amd64/bucklespring/download

then launch on terminal : buckle 

it works !!!

**Comment by alexmyczko** [comment]
wow 16.04, does anyone still run that? @tunnuz if not anymore, maybe close the issue?

**Comment by tunnuz** [comment]
Time to close this, I think. @alexmyczko thanks for the poke.
