### ISSUE TITLE
Add support for kFreeBSD and hurd

### ISSUE THREAD

**Issue by Natureshadow** [zevv/bucklespring#44]
In Debian, we found that bucklespring does not build on non-linux architectures because there is no code for the `scan()` function there.

Adding support for these kernels would be nice.

**Comment by Natureshadow** [comment]
Well, actually, `scan-linux` is not accurate at all. It should be `scan-x11` and it should properly detect X11, I think.

**Comment by zevv** [comment]
Quoting Dominik George (2017-01-25 16:36:51)

> Well, actually, `scan-linux` is not accurate at all. It should be
> `scan-x11` and it should properly detect X11, I think.

very true, I'll look into this.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
I'd like to avoid autoconf, would you be ok with passing an option to
make? something like

  make ARCH=X11

Quoting Dominik George (2017-01-25 16:36:51)
> Well, actually, `scan-linux` is not accurate at all. It should be `scan-x11` and it should properly detect X11, I think.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/zevv/bucklespring/issues/44#issuecomment-275140789


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by Natureshadow** [comment]
Well, your Makefile already assumes X11 for everything except WIndows and Mac anyway. So I'd just use this check to select the source file, instead of duplicating the OS check into the scan-* files.

See PR #45 if you like.

Also, if you created a release today, it'd go into Debian stretch (deadline today) ;).
