### ISSUE TITLE
Go to wayland instead of X11.

### ISSUE THREAD

**Issue by DmitryHetman** [zevv/bucklespring#49]

**Comment by zevv** [comment]
This might prove problematic: it seems that Wayland does not allow reading global key events for security reason, and thus does not provide an API to do so. If anyone can prove me wrong, let me know.

I guess the workaround would be to add support for reading raw `/dev/input/*` device input events, although that would require root access.

**Comment by zevv** [comment]
#wayland IRC channel confirms that Wayland lacks the hooks for global even grabbing. The best I can do is add libinput support to read events directly from the kernel. This will require permissions to open, read and write the /dev/input/* devices though.

Please try the latest head in git bb649b0217ce6fd1862a1b4c89bf93239730a302, compile with

```
make libinput=1
````
