### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by mechanette** [zevv/bucklespring#5]
The program crashes as soon as you press any key on the keyboard.
Log from the console:
```
Opening OpenAL audio device "Generic Software"
vkCode=68 scanCode=32 flags=0 time=347515
scancode 32/0x20
Loading audio file "./wav/20-1.wav"
```
And then just "buckle.exe has stopped working".

Using Windows 10, 64-bit (version 1607, OS build 14393.51)

**Comment by zevv** [comment]
yeah the win build is kind of broken. i got this working once but changed alut lib later which seems to have broken things. i dont own any windows machines myself so hard to fix for now, sorry about that

**Comment by zevv** [comment]
Closing this, personally I don't really care for win32 anyway - if anyone feels like fixing this, let me know!
