### ISSUE TITLE
4f-1.wav - failed to open file on Ubuntu 18.04

### ISSUE THREAD

**Issue by casperl** [zevv/bucklespring#70]
Hi,

Firstly, thanks a million for Bucklespring.  I have been looking for exactly this functionality for the past 14 years and finally found it.

I installed Buckle 1.4.0 on Ubuntu 18.04 from the standard Ubuntu repositories.  In an effort to reduce the volume level of the keyboard sounds (I frequently listen to podcasts while working on the PC) I experimented by starting buckle (the name of bucklespring in Ubuntu) with this command:

`buckle -g 20 `

While I cannot determine if any keyboard clicks are missing, this message appears on the terminal:

![image](https://user-images.githubusercontent.com/1303185/47148777-ecf0c500-d2d1-11e8-8f9a-d2f819068263.png)

Listing that directory in a terminal, the file 4f-1.wav does indeed not exist. 

It is also possible that this is an error specific to the Ubuntu package for Bucklespring.

Thanks in advance.

**Comment by casperl** [comment]
Update: I performed a git pull of bucklespring and there are more .wav file in that ./wav directory than in the Ubuntu 18.04 /usr/share/buckle/wav repository.  I copied the missing .wav files over manually and will report if errors persist.  

I presume I should open an error on Ubuntu (Launchpad?) to have this error fixed in their repositories?

**Comment by zevv** [comment]
Quoting Casper Labuschagne (2018-10-18 12:40:52)
> Update: I performed a git pull of bucklespring and there are more .wav file in that ./wav directory than in the Ubuntu 18.04 /usr/share/buckle/wav repository.  I copied the missing .wav files over manually and will report if errors persist.  
> 
> I presume I should open an error on Ubuntu (Launchpad?) to have this error fixed in their repositories?

Please do. I'll contact the Debian package maintainer to ask if he knows
about this.

Thanks,

Ico


--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
@Natureshadow You are the debian package maintainer for Bucklespring, right? Can you shed some light on this issue?

Thanks!

**Comment by casperl** [comment]
Reported as https://bugs.launchpad.net/ubuntu/+source/bucklespring/+bug/1798595 on Launchpad.
