### ISSUE TITLE
[Sugestion] Add mouse click sound also

### ISSUE THREAD

**Issue by pemartins1** [zevv/bucklespring#77]
I liked Bucklespring so much that I'd also like to have click noises for the mouse button clicks. Specially while using the touchpad it would be very useful.

**Comment by zevv** [comment]
I could look into this, but that would require audio samples from an
original IBM mouse, which I don't have.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by pemartins1** [comment]
I searched but unfortunately I could not find free sounds that specifically said that they came from an old IBM mouse.
Nevertheless, according to the click sounds I could hear in some Youtube videos I found searching for the terms "original IBM ps2 mouse", the clicks sounded to me like any other mouse click sounds.

These couple of files contain sounds that I believe are identical to what I could hear on the Youtube videos:
https://freesound.org/people/pikachu09/sounds/204612/
and
https://freesound.org/people/TheFlakesMaster/sounds/400659/

**Comment by zevv** [comment]
Mouse support added for Linux only - I don't have a windows or a mac to test, so I hope someone else can pick this up some day.

I'm not too fond of the mouse click sounds yet, the background noise and ambience does not match the keyboard sounds, but it is a start.

**Comment by zevv** [comment]
Sorry, forgot to push :(
