### ISSUE TITLE
Sound layouts?

### ISSUE THREAD

**Issue by zvezdochiot** [zevv/bucklespring#84]
Different sounds for different keyboard layouts?

And it is desirable to do this not the sounds themselves, but use tonal filters.

**Comment by eighteentee** [comment]
This would be a tremendous addition!

**Comment by ifohancroft** [comment]
I was about to suggest something similar:

Post a guide on the recodding process so ideally someone can donate Beamspring sounds (and perhaps other keyboards of interest) and add a vommand line option to choose which soundpack to use when starting.

**Comment by zvezdochiot** [comment]
30.05.2021 No actual.

**Comment by ifohancroft** [comment]
> 30.05.2021 No actual.

What?
