### ISSUE TITLE
Disable stereo effect.

### ISSUE THREAD

**Issue by codesoverhill** [zevv/bucklespring#93]
This is more of a query than an issue. How do I disable stereo effect in buckle? I have tried various numbers from 0 to 99 to '-s' option but I don't get mono effect.

I had to do this sudo ln -s libfluidsynth.so.2 libfluidsynth.so.1 to disable startup error of not finding libfluidsynth.so.1. Are stereo option and this related? I am using Linux Mint 20 Mate DE with Available audio devices: "OpenAL Soft".

Thank you.

**Comment by mcilrain** [comment]
I use the following command to make it mono (or close enough): `buckle -g 3000 -s 10000`.

**Comment by codesoverhill** [comment]
Thank you @mcilrain. That worked.
